#!/usr/bin/env node

const { spawn, exec } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 Nadar Vercel Deployment Pipeline...\n');

let expoProcess = null;

// Cleanup function
function cleanup() {
  console.log('\n🧹 Cleaning up processes...');
  if (expoProcess) {
    expoProcess.kill();
    console.log('✅ Expo stopped');
  }
  process.exit(0);
}

// Handle cleanup on exit
process.on('SIGINT', cleanup);
process.on('SIGTERM', cleanup);

function runCommand(command, cwd = process.cwd()) {
  return new Promise((resolve, reject) => {
    // Use npx for vercel commands to avoid PATH issues
    const actualCommand = command.replace(/^vercel\b/, 'npx vercel');
    console.log(`🔧 Running: ${actualCommand}`);
    exec(actualCommand, { cwd }, (error, stdout, stderr) => {
      if (error) {
        console.error(`❌ Error: ${error.message}`);
        reject(error);
        return;
      }
      if (stderr) {
        console.log(`⚠️  ${stderr}`);
      }
      console.log(stdout);
      resolve(stdout);
    });
  });
}

async function deployToVercel() {
  console.log('🌐 Deploying server to Vercel...');

  try {
    // Check if vercel CLI is installed
    try {
      await runCommand('vercel --version');
    } catch {
      console.log('📦 Installing Vercel CLI...');
      await runCommand('npm install -g vercel');
    }

    // Check if user is logged in
    try {
      await runCommand('vercel whoami');
    } catch {
      console.log('🔐 Please login to Vercel first:');
      console.log('   Run: vercel login');
      throw new Error('Not logged in to Vercel');
    }

    // Deploy to Vercel
    console.log('🚀 Deploying to Vercel...');
    const deployOutput = await runCommand('vercel --prod --yes');

    // Extract URL from output
    const urlMatch = deployOutput.match(/https:\/\/[^\s\n]+/);
    if (!urlMatch) {
      console.log('Deploy output:', deployOutput);
      throw new Error('Could not extract deployment URL from Vercel output');
    }

    const appUrl = urlMatch[0].replace(/\/$/, ''); // Remove trailing slash
    console.log(`✅ Deployment successful!`);
    console.log(`🌐 Server URL: ${appUrl}`);

    return appUrl;

  } catch (error) {
    console.error('❌ Deployment failed:', error.message);
    throw error;
  }
}

function updateAppConfig(serverUrl) {
  console.log(`📝 Updating app configuration to use: ${serverUrl}`);
  
  const envPath = path.join(__dirname, 'app', '.env');
  const envContent = `# Auto-generated by deploy-vercel.js
EXPO_PUBLIC_API_BASE=${serverUrl}
`;
  
  fs.writeFileSync(envPath, envContent);
  console.log('✅ App configuration updated');
}

function startExpo() {
  console.log('📱 Starting Expo with tunnel...');
  
  expoProcess = spawn('npx', ['expo', 'start', '--tunnel'], {
    cwd: path.join(__dirname, 'app'),
    stdio: ['ignore', 'pipe', 'pipe'],
    env: { ...process.env, FORCE_COLOR: '1' }
  });
  
  expoProcess.stdout.on('data', (data) => {
    const output = data.toString();
    console.log('EXPO:', output.trim());
  });
  
  expoProcess.stderr.on('data', (data) => {
    console.log('EXPO ERROR:', data.toString().trim());
  });
}

async function main() {
  try {
    // Step 1: Deploy to Vercel
    const serverUrl = await deployToVercel();
    
    // Step 2: Update app configuration
    updateAppConfig(serverUrl);
    
    // Step 3: Start Expo
    startExpo();
    
    console.log('\n🎉 Deployment pipeline complete!');
    console.log('📋 Summary:');
    console.log(`   🌐 Server: ${serverUrl}`);
    console.log('   📱 Expo: Starting with tunnel mode');
    console.log('\n⏳ Wait for Expo QR code to appear, then scan to test!');
    console.log('💡 Your server is now globally accessible!');
    console.log('💡 Press Ctrl+C to stop Expo (server will keep running)\n');
    
  } catch (error) {
    console.error('❌ Pipeline failed:', error.message);
    cleanup();
  }
}

main();
