@echo off
echo 🚀 Starting Nadar Development Pipeline with ngrok...
echo.

REM Kill any existing processes
taskkill /f /im ngrok.exe >nul 2>&1
taskkill /f /im node.exe >nul 2>&1

echo 🌐 Starting ngrok tunnel...
start /B ngrok http 4000

echo ⏳ Waiting for ngrok to initialize...
timeout /t 5 /nobreak >nul

REM Get ngrok URL and update app config
echo 📝 Getting ngrok URL and updating app configuration...
node -e "
const https = require('https');
const fs = require('fs');

setTimeout(async () => {
  try {
    const response = await fetch('http://localhost:4040/api/tunnels');
    const data = await response.json();
    const tunnel = data.tunnels.find(t => t.config.addr === 'localhost:4000');
    
    if (tunnel) {
      const ngrokUrl = tunnel.public_url;
      console.log('✅ ngrok URL:', ngrokUrl);
      
      const envContent = '# Auto-generated by dev-tunnel.bat\nEXPO_PUBLIC_API_BASE=' + ngrokUrl + '\n';
      fs.writeFileSync('app/.env', envContent);
      console.log('✅ App configuration updated');
    } else {
      console.log('❌ Could not get ngrok URL');
    }
  } catch (error) {
    console.log('❌ Error:', error.message);
  }
}, 3000);
"

echo.
echo 🖥️  Starting server...
start /B cmd /c "cd server && npm run dev"

timeout /t 3 /nobreak >nul

echo.
echo 📱 Starting Expo with tunnel...
cd app
start /B cmd /c "npx expo start --tunnel"

echo.
echo 🎉 Development pipeline started!
echo 📋 All services are starting in background...
echo 💡 Check the Expo terminal for QR code
echo 💡 Press any key to stop all services
pause >nul

echo.
echo 🧹 Stopping all services...
taskkill /f /im ngrok.exe >nul 2>&1
taskkill /f /im node.exe >nul 2>&1
echo ✅ All services stopped
