# Prometheus configuration for Nadar monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

# Scrape configuration
scrape_configs:
  # Nadar Server metrics
  - job_name: 'nadar-server'
    static_configs:
      - targets: ['nadar-server:4000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Health check monitoring
  - job_name: 'nadar-health'
    static_configs:
      - targets: ['nadar-server:4000']
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 5s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    # This target is optional and may not be available
