# Fly.io configuration for Nadar Server
app = "nadar-server"
primary_region = "fra"  # Frankfurt - good for global access

[build]

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm.mounts]]
  source = "nadar_data"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics"
